### ISSUE TITLE
az ébredő Neelakantan

### ISSUE THREAD

**Issue by makrai** [hlt-bme-hu/multiwsi#1]
elkezdtem összeírni [dolgokat](../wiki). A második pöttyben levő Neelakantanról beszéltem, léci nézd meg!

**Comment by DavidNemeskey** [comment]
A probléma a java és scala verziók összeakadásából származott; [bővebben lásd itt](http://stackoverflow.com/questions/24197836/compilation-failed-error-while-loading-annotatedelement-concurrentmap-charseq). A megoldás: a _pom.xml_ file-ban a  `<scala.version>`-t írd át `2.10.4`-re.
