### ISSUE TITLE
original Huang, MATLAB

### ISSUE THREAD

**Issue by makrai** [hlt-bme-hu/multiwsi#19]
http://www.socher.org/index.php/Main/ImprovingWordRepresentationsViaGlobalContextAndMultipleWordPrototypes

**Comment by gaebor** [comment]
@makrai Nincsen jogtiszta MatLab-om, sajnos a matek intézetnek lejártak a licenszei

**Comment by makrai** [comment]
megpróbálnád octave-val?

**Comment by makrai** [comment]
@DavidNemeskey  in the paper, write about both the orig Huang et al and CMultiVec

**Comment by DavidNemeskey** [comment]
We had a look at the code, and found that
1. the training code is only for their pre-GloVe embedding, the k-means part is not included
1. the test code is basically CRelabelCorpus from CMultiVec
1. in README.txt from the latter:

``` txt
The word representations use a dictionary of 100,232 words. 10 prototypes are used for
6,162 of the words, which roughly correspond to the most frequent words. To determine
which prototype to use given context, run run.m in matlab.
```

I am writing a mail to Huang to ask him how they arrived to those words.

**Comment by makrai** [comment]
Would you please also ask how they clustered the occurrences (to compute the prototypes)?

**Comment by makrai** [comment]
to write in the paper
- there is no code for the second part of the Huang paper
- CMultiVec is not adaptive

**Comment by DavidNemeskey** [comment]
No reply from Huang thus far, but I think it is not that important anyway. Once @kornai is done with the paper for today, I'll add those two sentences about this MSE.
