### ISSUE TITLE
POS tags on UMBC

### ISSUE THREAD

**Issue by DavidNemeskey** [hlt-bme-hu/multiwsi#3]
Since the best results is Neela vs LDOCE, it might be that Neela disambiguates POS tags
- compute the number of POS tags / word from UMBC
- validate against the other results

**Comment by makrai** [comment]
szerda

**Comment by DavidNemeskey** [comment]
@makrai @gaebor Na megcsináltam őket, az adatok itt vannak:
- `hlt/Work/MultiWSI/hom/{umbc,webkorpusz}.pos.hom.txt`: a POS "jelentésszámok"
- `hlt/Work/MultiWSI/results/{eng,hun}_vs_pos`: az eredmények
- mindnek van `.round` verziója is -- lásd lent

Ami látszik, hogy
- a magyarok semennyire sem korrelálnak a szófajjal
  - legalábbis Spearman és Pearson szerint
  - a KL divergencia mondjuk gyanúsan alacsony a szótáraknál és neelakantannál
- az angoloknál hasonló a helyzet
  - ami érdekes lehet, hogy a Collins Spearmane a szófajokkal 0.0626, míg az LDOCE-é 0.198 -- ennyiben megerősítve, amit eddig is tudtunk

Mondjuk azért az fontos, hogy a perplexitás nem optimális metrika, nagyon érzékeny az eloszlásra. Ezért csináltam olyan változatot is, ahol az első tizedesjegyet tartom csak meg. Nagy változások így sem történtek, de pl. a Collins--LDOCE pár így még látványosabb: 0.0517 vs 0.206.

**Comment by makrai** [comment]
(venv2)makrai@ron:/mnt/store/hlt/Work/MultiWSI/hom$ python ../scripts/sense_counts/compare_sense_counts.py webkorpusz.pos.hom.txt eksz.hom.txt 
words 1 & words 2 & shared words & Spearman & Pearson & KL & JS & cos & Cohen \
771790 & 67546 & 52158 & **0.0975** @ 1.97e-110 & 0.0647 @ 1.47e-49 & 0.02 & 0.00485 & 0.981 & 0.0498 \
(venv2)makrai@ron:/mnt/store/hlt/Work/MultiWSI/hom$ python ../scripts/sense_counts/compare_sense_counts.py webkorpusz.pos.hom.txt nszt.b.hom.txt 
words 1 & words 2 & shared words & Spearman & Pearson & KL & JS & cos & Cohen \
771790 & 5363 & 3532 & **0.0459** @ 0.00633 & 0.0672 @ 6.35e-05 & 0.0322 & 0.00814 & 0.967 & 0.0369 \

**Comment by DavidNemeskey** [comment]
Igen, láttam (a resultsban lévő file-ban is ott van), de itt a különbség fele a fentinek, ráadásul a p-value sem túl magas a másodiknál. Nekem egyébként az LDOCE (ami köztudottan szófaj szerint bont) korrelációja a szófajokkal is elég alacsonynak tűnt, de nyilván van egy csomó zavaró tényező...

**Comment by makrai** [comment]
Nem vitatom, amit írtál, csak bemásoltam a számokat. A POS-sal mostmár csak annyi, hogy bele kéne írni a cikkbe, hogy szerencsére nem POS-t tanulnak az embeddingek. Azért is bele kéne írni, mert eleve beszélt róla András.

**Comment by makrai** [comment]
@DavidNemeskey please write the details of your POS-merger method in the paper

**Comment by DavidNemeskey** [comment]
@makrai Értek én magyarul is :smile:
