### ISSUE TITLE
CMultiVec pre-trained

### ISSUE THREAD

**Issue by DavidNemeskey** [hlt-bme-hu/multiwsi#4]
Apparently there is one:
- _add it to the table_
- _see if it is adaptive_
- get rid of CMultiVec

**Comment by DavidNemeskey** [comment]
Leszedtem, és nem adaptív, viszont látszólag van valami módszerük annak eldöntésére, melyik szó többértelmű:

| Jelentésszámok | Szavak |
| --- | --: |
| 1 | 94 070 |
| 9 | 30 |
| 10 | 6 132 |
| Összesen | 100 232 |

The data is here: _/mnt/store/hlt/Language/English/Embed/multiprot/CMultiVec/release_zip/_. The files are:
- _vocab.txt_: the vocabulary
- _wordVectors.txt_: the original word vectors
- _vecs_meanings.txt_: the MWS vectors. I merged the original 10 files so that the format is the same as the output of CMultiVec
- _num_meanings.txt_: the word - #meanings mapping. I set the cosine similarity threshold to 0.99 and the zero threshold to 0.1.

**Comment by makrai** [comment]
* az összegzés nem cimmel: 94 e egyjelentésű, összesn 10 e
* közbülső jelentésszám nincs is?

2016-06-13 15:30 GMT+02:00 David Mark Nemeskey <notifications@github.com>:

**Comment by DavidNemeskey** [comment]
When I count the senses with _z05.s95_, I get

| Jelentésszámok | Szavak |
| --- | --: |
| 17 | 0 |
| 94053 | 1 |
| 1 | 7 |
| 5 | 8 |
| 158 | 9 |
| 5998 | 10 |

The words with 0 meanings are: astrogate, canyonside, conceivableness, containerful, degust, inmarry, iodocompound, negociate, prepossess, re-afforest, resplend, retem, shamanize, shoot-'em-up, undependability, unerect, washup.

**Comment by makrai** [comment]
an interesting distribution it is!

**Comment by DavidNemeskey** [comment]
I added Huang to the table, and the findings are:
- it correlates even better with LDOCE than Neelakantan
- it correlates very well with Neelakantan (0.349, which earns them the best English embedding correlation score)
- it correlates so well that ALL of Neela's vocabulary is in the intersection, making me suspect that they were trained on the same corpus

However, since neither are adaptive, this correlation only means that they agree on which words are multi-sense, and which words are not. Which is also useful, BTW, and we should definitely look into it -- it might even be a way to evaluate these methods on a simpler task.

In any case, I suggest we get rid of CMultiVec; maybe we could mention that we tried it but it sucked.

**Comment by DavidNemeskey** [comment]
@makrai, @kornai @gaebor Opinions?

**Comment by makrai** [comment]
pre-trained Huang: In my opinion, a system that tells unambiguous and ambiguous  words apart is definitely adaptive. Which is a claim on its own, as Huang et al is normally called uniform.
**C**MultiVec: we can drop the result and may or may not mention it.

**Comment by DavidNemeskey** [comment]
I am not sure about that. It is definitely adaptive to a certain extent, but does not go all the way. I think we should introduce an additional class when talking about these embeddings; I would go with 'non-adaptive -- binary -- fully adaptive' or sth. like that.

**Comment by makrai** [comment]
a comparison: the neela default is to learn max 2 senses

**Comment by makrai** [comment]
see the other Huang and CMultiVec issue
