### ISSUE TITLE
add missing correlatioins

### ISSUE THREAD

**Issue by makrai** [hlt-bme-hu/multiwsi#8]
- add AdaGram, jiweil vs Longman, CED 2x2
- _CMultiVec replace with pretrained (only English)_

**Comment by DavidNemeskey** [comment]
I guess first we need the data. :)

**Comment by makrai** [comment]
Which data do you miss?

**Comment by DavidNemeskey** [comment]
The AdaGram, Jiweil English (UMBC?) multiprot embeddings.

**Comment by gaebor** [comment]
I think it's in `/mnt/store/hlt/Language/English/Embed/multiprot/`

**Comment by DavidNemeskey** [comment]
Except they aren't, or at least not in the format I parsed for Hungarian.

**Comment by makrai** [comment]
umbc training has its own issue https://github.com/hlt-bme-hu/multiwsi/issues/16
I continue there
